// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package minisql

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse(context1 context.Context, s string) ([]Statement, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []Statement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]Statement, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []Statement); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Statement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockParser_Expecter) Parse(context1 interface{}, s interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", context1, s)}
}

func (_c *MockParser_Parse_Call) Run(run func(context1 context.Context, s string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(statements []Statement, err error) *MockParser_Parse_Call {
	_c.Call.Return(statements, err)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(context1 context.Context, s string) ([]Statement, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPageSaver creates a new instance of MockPageSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPageSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPageSaver {
	mock := &MockPageSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPageSaver is an autogenerated mock type for the PageSaver type
type MockPageSaver struct {
	mock.Mock
}

type MockPageSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPageSaver) EXPECT() *MockPageSaver_Expecter {
	return &MockPageSaver_Expecter{mock: &_m.Mock}
}

// Flush provides a mock function for the type MockPageSaver
func (_mock *MockPageSaver) Flush(context1 context.Context, pageIndex PageIndex) error {
	ret := _mock.Called(context1, pageIndex)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) error); ok {
		r0 = returnFunc(context1, pageIndex)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPageSaver_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockPageSaver_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - context1 context.Context
//   - pageIndex PageIndex
func (_e *MockPageSaver_Expecter) Flush(context1 interface{}, pageIndex interface{}) *MockPageSaver_Flush_Call {
	return &MockPageSaver_Flush_Call{Call: _e.mock.On("Flush", context1, pageIndex)}
}

func (_c *MockPageSaver_Flush_Call) Run(run func(context1 context.Context, pageIndex PageIndex)) *MockPageSaver_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageIndex
		if args[1] != nil {
			arg1 = args[1].(PageIndex)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPageSaver_Flush_Call) Return(err error) *MockPageSaver_Flush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPageSaver_Flush_Call) RunAndReturn(run func(context1 context.Context, pageIndex PageIndex) error) *MockPageSaver_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHeader provides a mock function for the type MockPageSaver
func (_mock *MockPageSaver) SaveHeader(context1 context.Context, databaseHeader DatabaseHeader) {
	_mock.Called(context1, databaseHeader)
	return
}

// MockPageSaver_SaveHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHeader'
type MockPageSaver_SaveHeader_Call struct {
	*mock.Call
}

// SaveHeader is a helper method to define mock.On call
//   - context1 context.Context
//   - databaseHeader DatabaseHeader
func (_e *MockPageSaver_Expecter) SaveHeader(context1 interface{}, databaseHeader interface{}) *MockPageSaver_SaveHeader_Call {
	return &MockPageSaver_SaveHeader_Call{Call: _e.mock.On("SaveHeader", context1, databaseHeader)}
}

func (_c *MockPageSaver_SaveHeader_Call) Run(run func(context1 context.Context, databaseHeader DatabaseHeader)) *MockPageSaver_SaveHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DatabaseHeader
		if args[1] != nil {
			arg1 = args[1].(DatabaseHeader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPageSaver_SaveHeader_Call) Return() *MockPageSaver_SaveHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPageSaver_SaveHeader_Call) RunAndReturn(run func(context1 context.Context, databaseHeader DatabaseHeader)) *MockPageSaver_SaveHeader_Call {
	_c.Run(run)
	return _c
}

// SavePage provides a mock function for the type MockPageSaver
func (_mock *MockPageSaver) SavePage(context1 context.Context, pageIndex PageIndex, page *Page) {
	_mock.Called(context1, pageIndex, page)
	return
}

// MockPageSaver_SavePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePage'
type MockPageSaver_SavePage_Call struct {
	*mock.Call
}

// SavePage is a helper method to define mock.On call
//   - context1 context.Context
//   - pageIndex PageIndex
//   - page *Page
func (_e *MockPageSaver_Expecter) SavePage(context1 interface{}, pageIndex interface{}, page interface{}) *MockPageSaver_SavePage_Call {
	return &MockPageSaver_SavePage_Call{Call: _e.mock.On("SavePage", context1, pageIndex, page)}
}

func (_c *MockPageSaver_SavePage_Call) Run(run func(context1 context.Context, pageIndex PageIndex, page *Page)) *MockPageSaver_SavePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageIndex
		if args[1] != nil {
			arg1 = args[1].(PageIndex)
		}
		var arg2 *Page
		if args[2] != nil {
			arg2 = args[2].(*Page)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPageSaver_SavePage_Call) Return() *MockPageSaver_SavePage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPageSaver_SavePage_Call) RunAndReturn(run func(context1 context.Context, pageIndex PageIndex, page *Page)) *MockPageSaver_SavePage_Call {
	_c.Run(run)
	return _c
}

// TotalPages provides a mock function for the type MockPageSaver
func (_mock *MockPageSaver) TotalPages() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalPages")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockPageSaver_TotalPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalPages'
type MockPageSaver_TotalPages_Call struct {
	*mock.Call
}

// TotalPages is a helper method to define mock.On call
func (_e *MockPageSaver_Expecter) TotalPages() *MockPageSaver_TotalPages_Call {
	return &MockPageSaver_TotalPages_Call{Call: _e.mock.On("TotalPages")}
}

func (_c *MockPageSaver_TotalPages_Call) Run(run func()) *MockPageSaver_TotalPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPageSaver_TotalPages_Call) Return(v uint32) *MockPageSaver_TotalPages_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPageSaver_TotalPages_Call) RunAndReturn(run func() uint32) *MockPageSaver_TotalPages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxPager creates a new instance of MockTxPager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxPager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxPager {
	mock := &MockTxPager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxPager is an autogenerated mock type for the TxPager type
type MockTxPager struct {
	mock.Mock
}

type MockTxPager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxPager) EXPECT() *MockTxPager_Expecter {
	return &MockTxPager_Expecter{mock: &_m.Mock}
}

// AddFreePage provides a mock function for the type MockTxPager
func (_mock *MockTxPager) AddFreePage(context1 context.Context, pageIndex PageIndex) error {
	ret := _mock.Called(context1, pageIndex)

	if len(ret) == 0 {
		panic("no return value specified for AddFreePage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) error); ok {
		r0 = returnFunc(context1, pageIndex)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxPager_AddFreePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFreePage'
type MockTxPager_AddFreePage_Call struct {
	*mock.Call
}

// AddFreePage is a helper method to define mock.On call
//   - context1 context.Context
//   - pageIndex PageIndex
func (_e *MockTxPager_Expecter) AddFreePage(context1 interface{}, pageIndex interface{}) *MockTxPager_AddFreePage_Call {
	return &MockTxPager_AddFreePage_Call{Call: _e.mock.On("AddFreePage", context1, pageIndex)}
}

func (_c *MockTxPager_AddFreePage_Call) Run(run func(context1 context.Context, pageIndex PageIndex)) *MockTxPager_AddFreePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageIndex
		if args[1] != nil {
			arg1 = args[1].(PageIndex)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxPager_AddFreePage_Call) Return(err error) *MockTxPager_AddFreePage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxPager_AddFreePage_Call) RunAndReturn(run func(context1 context.Context, pageIndex PageIndex) error) *MockTxPager_AddFreePage_Call {
	_c.Call.Return(run)
	return _c
}

// GetFreePage provides a mock function for the type MockTxPager
func (_mock *MockTxPager) GetFreePage(context1 context.Context) (*Page, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetFreePage")
	}

	var r0 *Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*Page, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *Page); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxPager_GetFreePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFreePage'
type MockTxPager_GetFreePage_Call struct {
	*mock.Call
}

// GetFreePage is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTxPager_Expecter) GetFreePage(context1 interface{}) *MockTxPager_GetFreePage_Call {
	return &MockTxPager_GetFreePage_Call{Call: _e.mock.On("GetFreePage", context1)}
}

func (_c *MockTxPager_GetFreePage_Call) Run(run func(context1 context.Context)) *MockTxPager_GetFreePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxPager_GetFreePage_Call) Return(page *Page, err error) *MockTxPager_GetFreePage_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockTxPager_GetFreePage_Call) RunAndReturn(run func(context1 context.Context) (*Page, error)) *MockTxPager_GetFreePage_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverflowPage provides a mock function for the type MockTxPager
func (_mock *MockTxPager) GetOverflowPage(context1 context.Context, pageIndex PageIndex) (*Page, error) {
	ret := _mock.Called(context1, pageIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetOverflowPage")
	}

	var r0 *Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) (*Page, error)); ok {
		return returnFunc(context1, pageIndex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) *Page); ok {
		r0 = returnFunc(context1, pageIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PageIndex) error); ok {
		r1 = returnFunc(context1, pageIndex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxPager_GetOverflowPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverflowPage'
type MockTxPager_GetOverflowPage_Call struct {
	*mock.Call
}

// GetOverflowPage is a helper method to define mock.On call
//   - context1 context.Context
//   - pageIndex PageIndex
func (_e *MockTxPager_Expecter) GetOverflowPage(context1 interface{}, pageIndex interface{}) *MockTxPager_GetOverflowPage_Call {
	return &MockTxPager_GetOverflowPage_Call{Call: _e.mock.On("GetOverflowPage", context1, pageIndex)}
}

func (_c *MockTxPager_GetOverflowPage_Call) Run(run func(context1 context.Context, pageIndex PageIndex)) *MockTxPager_GetOverflowPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageIndex
		if args[1] != nil {
			arg1 = args[1].(PageIndex)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxPager_GetOverflowPage_Call) Return(page *Page, err error) *MockTxPager_GetOverflowPage_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockTxPager_GetOverflowPage_Call) RunAndReturn(run func(context1 context.Context, pageIndex PageIndex) (*Page, error)) *MockTxPager_GetOverflowPage_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyPage provides a mock function for the type MockTxPager
func (_mock *MockTxPager) ModifyPage(context1 context.Context, pageIndex PageIndex) (*Page, error) {
	ret := _mock.Called(context1, pageIndex)

	if len(ret) == 0 {
		panic("no return value specified for ModifyPage")
	}

	var r0 *Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) (*Page, error)); ok {
		return returnFunc(context1, pageIndex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) *Page); ok {
		r0 = returnFunc(context1, pageIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PageIndex) error); ok {
		r1 = returnFunc(context1, pageIndex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxPager_ModifyPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyPage'
type MockTxPager_ModifyPage_Call struct {
	*mock.Call
}

// ModifyPage is a helper method to define mock.On call
//   - context1 context.Context
//   - pageIndex PageIndex
func (_e *MockTxPager_Expecter) ModifyPage(context1 interface{}, pageIndex interface{}) *MockTxPager_ModifyPage_Call {
	return &MockTxPager_ModifyPage_Call{Call: _e.mock.On("ModifyPage", context1, pageIndex)}
}

func (_c *MockTxPager_ModifyPage_Call) Run(run func(context1 context.Context, pageIndex PageIndex)) *MockTxPager_ModifyPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageIndex
		if args[1] != nil {
			arg1 = args[1].(PageIndex)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxPager_ModifyPage_Call) Return(page *Page, err error) *MockTxPager_ModifyPage_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockTxPager_ModifyPage_Call) RunAndReturn(run func(context1 context.Context, pageIndex PageIndex) (*Page, error)) *MockTxPager_ModifyPage_Call {
	_c.Call.Return(run)
	return _c
}

// ReadPage provides a mock function for the type MockTxPager
func (_mock *MockTxPager) ReadPage(context1 context.Context, pageIndex PageIndex) (*Page, error) {
	ret := _mock.Called(context1, pageIndex)

	if len(ret) == 0 {
		panic("no return value specified for ReadPage")
	}

	var r0 *Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) (*Page, error)); ok {
		return returnFunc(context1, pageIndex)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageIndex) *Page); ok {
		r0 = returnFunc(context1, pageIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Page)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PageIndex) error); ok {
		r1 = returnFunc(context1, pageIndex)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxPager_ReadPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadPage'
type MockTxPager_ReadPage_Call struct {
	*mock.Call
}

// ReadPage is a helper method to define mock.On call
//   - context1 context.Context
//   - pageIndex PageIndex
func (_e *MockTxPager_Expecter) ReadPage(context1 interface{}, pageIndex interface{}) *MockTxPager_ReadPage_Call {
	return &MockTxPager_ReadPage_Call{Call: _e.mock.On("ReadPage", context1, pageIndex)}
}

func (_c *MockTxPager_ReadPage_Call) Run(run func(context1 context.Context, pageIndex PageIndex)) *MockTxPager_ReadPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageIndex
		if args[1] != nil {
			arg1 = args[1].(PageIndex)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxPager_ReadPage_Call) Return(page *Page, err error) *MockTxPager_ReadPage_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockTxPager_ReadPage_Call) RunAndReturn(run func(context1 context.Context, pageIndex PageIndex) (*Page, error)) *MockTxPager_ReadPage_Call {
	_c.Call.Return(run)
	return _c
}
